heat_template_version: 2015-04-30

parameters:
  ControlPlaneIpList:
    default: []
    type: comma_delimited_list
  ExternalIpList:
    default: []
    type: comma_delimited_list
  InternalApiIpList:
    default: []
    type: comma_delimited_list
  SDNinternalIpList:
    default: []
    type: comma_delimited_list   
  SDNnorthboundIpList:
    default: []
    type: comma_delimited_list 
  SDNsouthboundIpList:
    default: []
    type: comma_delimited_list 
  SDNmanagementIpList:
    default: []
    type: comma_delimited_list              
  StorageIpList:
    default: []
    type: comma_delimited_list
  StorageMgmtIpList:
    default: []
    type: comma_delimited_list
  TenantIpList:
    default: []
    type: comma_delimited_list
  ManagementIpList:
    default: []
    type: comma_delimited_list

outputs:
  net_ip_map:
    description: >
      A Hash containing a mapping of network names to assigned lists
      of IP addresses.
    value:
      ctlplane: {get_param: ControlPlaneIpList}
      external: {get_param: ExternalIpList}
      internal_api: {get_param: InternalApiIpList}
      sdn_internal: {get_param: SDNinternalIpList}
      sdn_northbound: {get_param: SDNnorthboundIpList}
      sdn_southbound: {get_param: SDNsouthboundIpList}
      sdn_management: {get_param: SDNmanagementIpList}
      storage: {get_param: StorageIpList}
      storage_mgmt: {get_param: StorageMgmtIpList}
      tenant: {get_param: TenantIpList}
      management: {get_param: ManagementIpList}
