heat_template_version: 2015-04-30

parameters:
  ControlPlaneIp:
    default: ''
    type: string
  ExternalIp:
    default: ''
    type: string
  ExternalIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  InternalApiIp:
    default: ''
    type: string
  InternalApiIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  SDNinternalIp:
    default: ''
    type: string
  SDNinternalIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6    
  SDNnorthboundIp:
    default: ''
    type: string
  SDNnorthboundIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  SDNsouthboundIp:
    default: ''
    type: string
  SDNsouthboundIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  SDNmanagementIp:
    default: ''
    type: string
  SDNmanagementIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6                        
  StorageIp:
    default: ''
    type: string
  StorageIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  StorageMgmtIp:
    default: ''
    type: string
  StorageMgmtIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  TenantIp:
    default: ''
    type: string
  TenantIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  ManagementIp:
    default: ''
    type: string
  ManagementIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6

outputs:
  net_ip_map:
    description: >
      A Hash containing a mapping of network names to assigned IPs
      for a specific machine.
    value:
      ctlplane: {get_param: ControlPlaneIp}
      external: {get_param: ExternalIp}
      internal_api: {get_param: InternalApiIp}
      sdn_internal: {get_param: SDNinternalIp}
      sdn_northbound: {get_param: SDNnorthboundIp}
      sdn_southbound: {get_param: SDNsouthboundIp}
      sdn_management: {get_param: SDNmanagementIp}
      storage: {get_param: StorageIp}
      storage_mgmt: {get_param: StorageMgmtIp}
      tenant: {get_param: TenantIp}
      management: {get_param: ManagementIp}
  net_ip_uri_map:
    description: >
      A Hash containing a mapping of netowrk names to assigned IPs for a
      specific machine with brackets around IPv6 addresses for use in URLs.
    value:
      ctlplane: {get_param: ControlPlaneIp}
      external: {get_param: ExternalIpUri}
      internal_api: {get_param: InternalApiIpUri}
      sdn_internal: {get_param: SDNinternalIpUri}
      sdn_northbound: {get_param: SDNnorthboundIpUri}
      sdn_southbound: {get_param: SDNsouthboundIpUri}
      sdn_management: {get_param: SDNmanagementIpUri}      
      storage: {get_param: StorageIpUri}
      storage_mgmt: {get_param: StorageMgmtIpUri}
      tenant: {get_param: TenantIpUri}
      management: {get_param: ManagementIpUri}
