heat_template_version: 2015-04-30

description: >
  Creates a port on the sdn_management network.

parameters:
  SDNmanagementNetName:
    description: Name of the SDN management neutron network
    default: sdn_management
    type: string
  PortName:
    description: Name of the port
    default: ''
    type: string
  ControlPlaneIP: # Here for compatibility with noop.yaml
    description: IP address on the control plane
    default: ''
    type: string
  FixedIPs:
    description: >
        Control the IP allocation for the VIP port. E.g.
        [{'ip_address':'1.2.3.4'}]
    default: []
    type: json
  IPPool: # Here for compatibility with from_pool.yaml
    default: {}
    type: json
  NodeIndex: # Here for compatibility with from_pool.yaml
    default: 0
    type: number
  NetworkName:
    description: # Here for compatibility with vip.yaml
    default: sdn_management
    type: string

resources:

  SDNmanagementPort:
    type: OS::Neutron::Port
    properties:
      network: {get_param: SDNmanagementNetName}
      name: {get_param: PortName}
      fixed_ips: {get_param: FixedIPs}
      replacement_policy: AUTO

outputs:
  ip_address:
    description: SDN management network IP
    value: {get_attr: [SDNmanagementPort, fixed_ips, 0, ip_address]}
  ip_address_uri:
    description: |
        SDN management network IP
    value: {get_attr: [SDNmanagementPort, fixed_ips, 0, ip_address]}
  ip_subnet:
    # FIXME: this assumes a 2 digit subnet CIDR (need more heat functions?)
    description: IP/Subnet CIDR for the SDN management network IP
    value:
          list_join:
            - ''
            - - {get_attr: [SDNmanagementPort, fixed_ips, 0, ip_address]}
              - '/'
              - {get_attr: [SDNmanagementPort, subnets, 0, cidr, -2]}
              - {get_attr: [SDNmanagementPort, subnets, 0, cidr, -1]}
