heat_template_version: 2015-04-30

description: Create networks to split out Overcloud traffic

resources:

  ExternalNetwork:
    type: OS::TripleO::Network::External

  InternalNetwork:
    type: OS::TripleO::Network::InternalApi

  StorageMgmtNetwork:
    type: OS::TripleO::Network::StorageMgmt

  StorageNetwork:
    type: OS::TripleO::Network::Storage

  TenantNetwork:
    type: OS::TripleO::Network::Tenant

  ManagementNetwork:
    type: OS::TripleO::Network::Management

  SDNinternalNetwork:
    type: OS::TripleO::Network::SDNinternal

  SDNnorthboundNetwork:
    type: OS::TripleO::Network::SDNnorthbound

  SDNsouthboundNetwork:
    type: OS::TripleO::Network::SDNsouthbound

  SDNmanagementNetwork:
    type: OS::TripleO::Network::SDNmanagement
